services:
  db:
    container_name: postgres-db
    image: postgres:16.6-bullseye
    restart: always
    environment:
      DB_URL: postgres://postgres:12345burnedout54321@db:5432/burnedout
      DB_PORT: 5432
      POSTGRES_HOST: db
      POSTGRES_DB: burnedout
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 12345burnedout54321
    ports:
      - "5432:5432"
    profiles:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d burnedout"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app/next-app
    restart: always
    ports:
      - 3000:3000
    # depends_on:
    #   db:
    #     condition: service_healthy
    env_file:
      - .env
    environment:
      DB_URL: postgres://postgres:12345burnedout54321@db:5432/burnedout
      DB_PORT: 5432
      POSTGRES_HOST: db
      POSTGRES_DB: burnedout
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 12345burnedout54321
  
volumes:
  pgdata: {}
